LUISMVC/LUISMVC/Models/Containers/CreateContainerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LUISMVC.Models.Containers
{
    public class CreateContainerViewModel
    {
        
        public string Gkey { get; set; }

        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Equipo")]
        public string EquipmentNbr { get; set; }

        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Tipo Iso")]
        public string TypeIso { get; set; }

        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Owner")]
        public string Own { get; set; }

        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Type Length")]
        public string TypeLength { get; set; }

        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Tare Weight")]
        public int TareWt { get; set; }

        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Safe Weight")]
        public int SafeWt { get; set; }

    }

   

}

LUISMVC/LUISMVC/Models/Containers/EditContainerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace LUISMVC.Models.Containers
{
    public class EditContainerViewModel
    {
        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Equipo")]
        public string EquipmentNbr { get; set; }

        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Tipo Iso")]
        public string TypeIso { get; set; }

        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Owner")]
        public string Own { get; set; }

        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Type Length")]
        public string TypeLength { get; set; }

        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Tare Weight")]
        public int TareWt { get; set; }

        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Safe Weight")]
        public int SafeWt { get; set; }
    }
}

LUISMVC/LUISMVC/Controllers/ContainersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LUISMVC.DB;
using System.Text;
using System.ServiceModel;
using System.Runtime.Serialization;
using LUISMVC.Models.Containers;


namespace LUISMVC.Controllers
{
    public class ContainersController : Controller
    {
        private Koala3Entities db = new Koala3Entities();


        //////////////////////////////////////////////////// GET: Containers
        public ActionResult Index()
        {
            var srvc = new wscontainer.Service1Client();
           return View(srvc.ListadoContainer().ToList());

            // return View(db.Containers.ToList());
        }



        /////////////////////////////////////////////////// GET: Containers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           // Container container = db.Containers.Find(id);
            var srvc = new wscontainer.Service1Client();

            if (srvc == null)
            {
                return HttpNotFound();
            }
            return View(srvc);
        }

        ////////////////////////////////// GET: Containers/Create
        [HttpGet] 
        public ActionResult Create()
        {
            return View(new CreateContainerViewModel());
        }

        [HttpPost]
        public ActionResult CreateContainer(CreateContainerViewModel container)
        {
       
                using (wscontainer.Service1Client db = new wscontainer.Service1Client())
                {


                    db.crearregistro(AutoMapper.Mapper.Map<CreateContainerViewModel,wscontainer.Container>(container));

                    return RedirectToAction("Index");
                }
            
        }


        /////////////////////////////////////////////////////////////////// GET: Containers/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            using (wscontainer.Service1Client db = new wscontainer.Service1Client())
            {
                

                var cont = db.getcontainer(id);

                var container = AutoMapper.Mapper.Map<wscontainer.Container, CreateContainerViewModel>(cont);

                return View(container);

            }

        }

        // POST: Containers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CreateContainerViewModel container)
        {

            using (wscontainer.Service1Client db = new wscontainer.Service1Client())
            {

                db.editarregistro(AutoMapper.Mapper.Map<CreateContainerViewModel, wscontainer.Container>(container));
      

                return RedirectToAction("Index");
            }

                
        }






        // GET: Containers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Container container = db.Containers.Find(id);
            if (container == null)
            {
                return HttpNotFound();
            }
            return View(container);
        }

        // POST: Containers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Container container = db.Containers.Find(id);
            db.Containers.Remove(container);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LUISMVC/LUISMVC/Views/Containers/Create.cshtml
@model LUISMVC.Models.Containers.CreateContainerViewModel

@*@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}*@

<h2>Create</h2>


@using (Html.BeginForm("Createcontainer", "Containers" , FormMethod.Post )) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Container</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EquipmentNbr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EquipmentNbr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EquipmentNbr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeIso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeIso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypeIso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Own, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Own, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Own, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeLength, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeLength, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypeLength, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TareWt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TareWt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TareWt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SafeWt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SafeWt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SafeWt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Creates" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LUISMVC/LUISMVC/Views/Containers/Delete.cshtml
@model LUISMVC.DB.Container

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Container</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.equipmentNbr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.equipmentNbr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.typeIso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.typeIso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.own)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.own)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.typeLength)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.typeLength)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tareWt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tareWt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.safeWt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.safeWt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LUISMVC/LUISMVC/Views/Containers/Details.cshtml
@model LUISMVC.wscontainer.Container
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Container</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.equipmentNbr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.equipmentNbr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.typeIso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.typeIso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.own)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.own)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.typeLength)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.typeLength)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tareWt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tareWt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.safeWt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.safeWt)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.gkey }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LUISMVC/LUISMVC/Views/Containers/Edit.cshtml
@model LUISMVC.Models.Containers.CreateContainerViewModel


<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Container</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Gkey)

        <div class="form-group">
            @Html.LabelFor(model => model.EquipmentNbr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EquipmentNbr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EquipmentNbr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeIso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeIso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypeIso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Own, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Own, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Own, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeLength, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeLength, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypeLength, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TareWt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TareWt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TareWt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SafeWt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SafeWt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SafeWt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LUISMVC/LUISMVC/Views/Containers/Index.cshtml
@model IEnumerable<LUISMVC.wscontainer.Container>

@{
    ViewBag.Title = "CONTAINERS";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.equipmentNbr)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.typeIso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.own)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.typeLength)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tareWt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.safeWt)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.equipmentNbr)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.typeIso)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.own)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.typeLength)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tareWt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.safeWt)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.gkey }) |
            @Html.ActionLink("Details", "Details", new { id=item.gkey }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.gkey })
        </td>
    </tr>
}

</table>